machine:
  pre:
    -
  services:
    - docker

dependencies:
  cache_directories:
    - "vendor/"

  override:
    - docker build circleci/docker/php -t parallel/php:5.6
    - bin/composer install

test:
  override:
    - ./circleci/bin/php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

  post:
    - ./circleci/bin/php vendor/bin/test-reporter
